### PR TITLE
Bump ingress API version due to deprecation in k8s 1.16

### PR DESCRIPTION
**Pull request by lgg42**
K8s 1.16 is deprecating the ingress object API: https://kubernetes.io/blog/2019/07/18/api-deprecations-in-1-16/
The new ingress API version **networking.k8s.io/v1beta1** is available since k8s 1.14
This PR is in order for teams migrating to k8s >=1.16 be still able to use Kamus from the upstream chart repository.

### CODE REVIEW

**Comment by lgg42** [comment]
Hello there??

**Comment by mcanaves** [comment]
@shaikatz or @omerlh any suggestion?

**Comment by shaikatz** [comment]
It was totally missed by us, we are sorry. 
Anyway, the beta ingress is available until 1.22.
I'll merge it now since that's a change that should happen.

**Comment by mcanaves** [comment]
Thanks!

**Pull request merged**
